### ISSUE TITLE
how to send setChargingProfile

### ISSUE THREAD

**Issue by bastokr** [ChargeTimeEU/Java-OCA-OCPP#144]
I don't know how to  send   setChargingProfile  Central to Client

my test case has  error Code

server.sendSetChargingProfileRequest(  0,serverOpt.getCsChargingProfiles());

using this method 

  public void sendSetChargingProfileRequest(Integer connectorId, ChargingProfile csChargingProfiles)
      throws Exception {
    SetChargingProfileRequest request =
        new SetChargingProfileRequest(connectorId, csChargingProfiles);
    send(request);
  }

ERROR [2021-05-26 16:27:24,367] (Draft_6455.java[logRuntimeException]:874) - Runtime exception during onWebsocketMessage
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.google.gson.JsonArray.get(JsonArray.java:183)
	at eu.chargetime.ocpp.JSONCommunicator.parse(JSONCommunicator.java:145)
	at eu.chargetime.ocpp.Communicator$EventHandler.receivedMessage(Communicator.java:272)
	at eu.chargetime.ocpp.WebSocketReceiver.relay(WebSocketReceiver.java:44)
	at eu.chargetime.ocpp.WebSocketListener$1.onMessage(WebSocketListener.java:132)
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:673)
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:885)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:819)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1046)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1028)
ERROR [2021-05-26 16:27:24,368] (WebSocketListener.java[onError]:147) - On error (resource descriptor: /) triggered:
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.google.gson.JsonArray.get(JsonArray.java:183)
	at eu.chargetime.ocpp.JSONCommunicator.parse(JSONCommunicator.java:145)
	at eu.chargetime.ocpp.Communicator$EventHandler.receivedMessage(Communicator.java:272)
	at eu.chargetime.ocpp.WebSocketReceiver.relay(WebSocketReceiver.java:44)
	at eu.chargetime.ocpp.WebSocketListener$1.onMessage(WebSocketListener.java:132)
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:673)
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:885)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:819)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1046)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1028)

**Comment by robert-s-ubi** [comment]
Looks like the Charging Station returned a malformed CALLERROR message. You should try to extract the raw JSON that was received (e.g. by copying line 150 in JSONCommunicator.java after line 144) and post it here:

    } else if (array.get(INDEX_MESSAGEID).getAsInt() == TYPENUMBER_CALLERROR) {
      message = new CallErrorMessage();
+      logger.error("Received CALLERROR: {}", json.toString());
      ((CallErrorMessage) message).setErrorCode(array.get(INDEX_CALLERROR_ERRORCODE).getAsString());
      ((CallErrorMessage) message)
          .setErrorDescription(array.get(INDEX_CALLERROR_DESCRIPTION).getAsString());
      ((CallErrorMessage) message).setRawPayload(array.get(INDEX_CALLERROR_PAYLOAD).toString());
    } else {
      logger.error("Unknown message type of message: {}", json.toString());
      throw new IllegalArgumentException("Unknown message type");
    }

**Comment by TVolden** [comment]
Thank you @robert-s-ubi, you are a big help. I really appreciate it.

@bastokr did you solve your problem? If so, can I get you to close the issue?

**Comment by bastokr** [comment]
Thanks so much for your help ^^
