### ISSUE TITLE
ChargingProfile with RemoteStartTransactionRequest problem

### ISSUE THREAD

**Issue by M1chaela** [ChargeTimeEU/Java-OCA-OCPP#71]
I'm trying to set chargingProfile on RemoteStartTransactionRequest, but it returns CallErrorException.  It works fine when sending the request without the chargingProFile.

This is the code for chargingProfile:

 ```
ChargingSchedulePeriod[] chargingSchedulePeriod = new ChargingSchedulePeriod[1];
chargingSchedulePeriod[0] = new ChargingSchedulePeriod(1, 32);
ChargingSchedule chargingSchedule = new ChargingSchedule(ChargingRateUnitType.A, chargingSchedulePeriod);

ChargingProfile chargingProfile = new ChargingProfile();
chargingProfile.setChargingSchedule(chargingSchedule);
chargingProfile.setStackLevel(1);
chargingProfile.setChargingProfileId(1);
chargingProfile.setChargingProfilePurpose(ChargingProfilePurposeType.ChargePointMaxProfile);
chargingProfile.setChargingProfileKind(ChargingProfileKindType.Recurring);

request.setChargingProfile(chargingProfile);
```
And the exception:
```
eu.chargetime.ocpp.CallErrorException
at eu.chargetime.ocpp.Server$1.handleError(Server.java:111)
    at eu.chargetime.ocpp.Session$CommunicatorEventHandler.onError(Session.java:211)
    at eu.chargetime.ocpp.Communicator$EventHandler.receivedMessage(Communicator.java:250)
    at eu.chargetime.ocpp.WebSocketReceiver.relay(WebSocketReceiver.java:44)
    at eu.chargetime.ocpp.WebSocketListener$1.onMessage(WebSocketListener.java:121)
    at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:569)
    at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:696)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
    at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:906)
```

The message from Communicator.java:250
OccurenceConstraintViolation - Payload for Action is syntactically correct but at least one of the fields violates occurence constraints

**Comment by M1chaela** [comment]
ok so I found out that the error is thrown when client uses an older version of the library. I'd have to check if we can update to the newest version.

**Comment by TVolden** [comment]
Ah okay. Well at least it's tested now. I'll close the issue. 😀
